appName: "app"
cassandra:
  hosts: ["cassandra"]
  port: 9042
  keyspaces: ["btcusdt"]
  tables: [one_second, one_minute]

sparkConfig:
  spark.local.dir: 'D:\spark\temp'
  spark.sql.adaptive.enabled: "false"
  spark.sql.streaming.forceDeleteTempCheckpointLocation: "true"
  spark.sql.shuffle.partitions: "3"
  spark.cassandra.connection.host: "cassandra"
  spark.cassandra.connection.port: "9042"
  spark.sql.extensions: "com.datastax.spark.connector.CassandraSparkExtensions"
  spark.sql.streaming.statefulOperator.checkCorrectness.enabled: "false"
