version: "3.8"
services:
  zookeeper:
    container_name: zookeeper
    build:
      context: ./kafka_cluster/zookeeper
      dockerfile: ./kafka_cluster/zookeeper/Dockerfile
    ports:
      - "2181:2181"
    networks:
      - etl

  kafka:
    container_name: kafka_broker
    depends_on:
      - "zookeeper"
    build:
      context: ./kafka_cluster/broker
      dockerfile: ./kafka_cluster/broker/Dockerfile
    ports:
      - "9092:9092"
    networks:
      - etl

  cassandra:
    build:
      context: ./cassandra_cluster
      dockerfile: ./cassandra_cluster/Dockerfile
    ports: 
      - "9042:9042"
    environment:
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
      
    networks:
      - backend
      - etl

  web_client:
    depends_on:
    - web_server
    build:
      context: ./web_client
      dockerfile: ./web_client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /web_client
      - '/app/node_modules'
    networks:
      - frontend
    

  web_server:
    build:
      context: ./web_server    
      dockerfile: ./web_server/Dockerfile
    ports:
      - "9001:9001"
    environment:
      - WEB_HOST=127.0.0.1
      - WEB_PORT=9001
      - DB_HOSTS=0.0.0.0
      - DB_PORT=9042
    networks:
      - backend
      - frontend

  
networks:
  etl:
    name: etl
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge


  
